name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/checkout@v4
        with:
           repository: ''
      - run: ls
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}

# checkout
# ls
# docker build
# docker images
# docker push
# pas de credential en clair
