name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/checkout@v4
        with:
           repository: ''
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: semver
          increment: patch
      - run: ls
      - run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/getting-started:${{ steps.version.outputs.version }} .
      - run: docker images
      - run: docker login
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push ${{ vars.DOCKERHUB_USERNAME }}/getting-started:${{ steps.version.outputs.version }}


# checkout
# ls
# docker build
# docker images
# docker push
# pas de credential en clair
