name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/checkout@v4
        with:
           repository: ''
      - run: ls
      - run: docker build -t getting-started .
      - run: docker images
      - run: docker login
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker tag getting-started ${{ vars.DOCKERHUB_USERNAME }}/getting-started
      - run: docker push ${{ vars.DOCKERHUB_USERNAME }}/getting-started


# checkout
# ls
# docker build
# docker images
# docker push
# pas de credential en clair
