name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/checkout@v4
        with:
           repository: ''
      - run: ls

# checkout
# ls
# docker build
# docker images
# docker push
# pas de credential en clair
